container-name-run : "textbot-swift-run"
container-name-tools : "textbot-swift-tools"
image-name-run : "textbot-swiftrun"
image-name-tools: "textbot-swifttools"
dockerfile-tools: "Dockerfile-tools"
dockerfile-run: "Dockerfile"
build-cmd-debug : "/root/utils/tools-utils.sh build debug"
debug-cmd : "/root/utils/tools-utils.sh debug text-bot 1024"
build-cmd-run : "/root/utils/tools-utils.sh build release"
run-cmd : "/root/utils/run-utils.sh run text-bot"
test-cmd : "/root/utils/tools-utils.sh test"
container-path-run : "/root/project"
container-path-tools : "/root/project"
container-port-map : "8080:8080"
container-port-map-debug : "1024:1024,1025:1025"
